choco install -y 7zip
choco install -y chocolateygui
choco install -y classic-shell
choco install -y discord
choco install -y dropbox
choco install -y git
choco install -y GoogleChrome
choco install -y googledrive
choco install -y imdisk
choco install -y openhardwaremonitor
choco install -y paint.net
choco install -y python
choco install -y python3
choco install -y qbittorrent
choco install -y vlc
choco install -y vscode
choco install -y DotNet4.5.2
choco install -y dotnet4.7.1
choco install -y KB2919355
choco install -y KB2919442
